<script setup lang="ts">
const hoverClass = "transform-content origin-center transition-transform hover:scale-110";
const infoClass = "absolute p-4 rounded-xl max-w-sm text-sm";

const hovered = ref<"black" | "blue" | "green" | "yellow" | "red" | null>(null);
</script>

<template>
	<div class="mx-auto max-w-[800px]">
		<div class="relative">
			<svg width="100%" height="100%" viewBox="0 0 3543 3543" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/">
				<LogoBlack :class="hoverClass" @mouseenter="hovered = 'black'" @mouseleave="hovered = null" />
				<LogoBlue :class="hoverClass" @mouseenter="hovered = 'blue'" @mouseleave="hovered = null" />
				<LogoGreen :class="hoverClass" @mouseenter="hovered = 'green'" @mouseleave="hovered = null" />
				<LogoYellow :class="hoverClass"  @mouseenter="hovered = 'yellow'" @mouseleave="hovered = null"/>
				<LogoRed :class="hoverClass" @mouseenter="hovered = 'red'" @mouseleave="hovered = null" />
			</svg>
			<Transition>
				<div v-show="hovered === 'black'" :class="`${infoClass} dark bg-[#232020] text-foreground top-0 left-1/2 -translate-x-1/2`">
					<b>SUPPORTING</b> Indigenous Peoples’ rights and interests, and authority to control their data.

					Indigenous Data Commons platform supports Aboriginal and Torres Strait Islander communities <b>MANAGE</b> and <b>SHARE</b> data freely and cooperatively.
				</div>
			</Transition>
			<Transition>
				<div v-show="hovered === 'blue'" :class="`${infoClass} bg-isu-blue text-isu-blue-foreground top-1/5 -left-1/5`">
					<b>THE INDIGENOUS DATA NETWORK</b> defines Indigenous data as all data generated by, about, or for Aboriginal and Torres Strait Islander people in Australia.
				</div>
			</Transition>
			<Transition>
				<div v-show="hovered === 'green'" :class="`${infoClass} bg-isu-green text-isu-green-foreground top-5/6 left-0`">
					<div class="font-bold">DESCRIBE</div>

					Collected, analysed, and <b>INTERPRETED</b> within the context of Indigenous communities, cultures, and knowledge systems.
				</div>
			</Transition>
			<Transition>
				<div v-show="hovered === 'yellow'" :class="`${infoClass} bg-isu-yellow text-isu-yellow-foreground top-0 left-3/5`">
					<div class="font-bold">FIND</div>

					<b>COLLECTED</b>, analysed, and interpreted within the context of Indigenous communities, cultures, and knowledge systems.
				</div>
			</Transition>
			<Transition>
				<div v-show="hovered === 'red'" :class="`${infoClass} bg-isu-red text-isu-red-foreground top-5/6 right-0`">
					<div class="font-bold">RECORD</div>

					Collected, <b>ANALYSED</b>, and interpreted within the context of Indigenous communities, cultures, and knowledge systems.
				</div>
			</Transition>
		</div>
	</div>
</template>

<style scoped>
.v-enter-active,
.v-leave-active {
	transition: opacity 0.5s ease;
}

.v-enter-from,
.v-leave-to {
	opacity: 0;
}
</style>