export const publications: PublicationItem[] = [
    {
    title: "Framework for the Governance of Indigenous Data: HASS and Indigenous Research Data Commons",
    author: ["Langton, M., McLellan, R., Fewster, J., & Smith, K."],
    date: "2026",
    publisher: "Australian Research Data Commons",
    url: "https://doi.org/10.5281/zenodo.11135961",
    idn: true,
    },
    {
        title: "Developing and Adopting Indigenous Data Governance Frameworks: A report of the Indigenous Data Network Roundtable 2024 (Version 1)",
        author: ["LANGTON, M., SMITH, K., Clarke, A., Murray, L.-C., Curkpatrick, S., MURRAY, L., Corporal, S., Bones, J., Lee, A., Reweti, E., Gray, A., & RITTE, R."],
        date: "2026",
        publisher: "The University of Melbourne",
        url: "https://doi.org/10.26188/31360507.v1",
        idn: true,
    },
    {
        title: "Improving Indigenous Data Capabilities in Indigenous Organisations: A report of the Indigenous Data Network Roundtable 2022.",
        description: "",
        date: "2026",
        author: ["LANGTON, M., SMITH, K., Murray, L.-C., Curkpatrick, S., Clarke, A., Corporal, S., RITTE, R., MURRAY, L., Bones, J., Lee, A., & Reweti, E."],
        img: "",
        url: "https://doi.org/10.26188/31360348",
        publisher: "",
        idn: true,
    },
    {
        title: "Current Data Governance Models lack clear recognition of Indigenous jurisdiction over data.",
        description: "",
        date: "2025-11-27",
        author: ["Smith, K., & Clarke, A."],
        img: "",
        url: "",
        publisher: "Caring for Indigenous data in museums and research, Musée du quai Branly – Jacques Chirac, Paris.",
        idn: true,
    },
    {
        title: "IDN Themes vocabulary",
        description: "",
        date: "2025",
        author: ["Indigenous Data Network"],
        img: "",
        url: "https://data.idnau.org/pid/vocab/idn-th",
        publisher: "The University of Melbourne",
        idn: true,
    },
    {
        title: "IDN Catalogue Profile specification",
        description: "",
        date: "2025",
        author: ["Indigenous Data Network"],
        img: "",
        url: "https://data.idnau.org/pid/cp/spec",
        publisher: "The University of Melbourne",
        idn: true,
    },
    {
        title: "Practical guidelines for Indigenous research: lessons from a case study exploring data literacy in our local Aboriginal and Torres Strait Islander community.",
        description: "",
        date: "2025",
        author: ["Cook B., Corporal S., Mengersen K."],
        img: "",
        url: "https://doi.org/10.1177/11771801251398574",
        publisher: "lterNative: An International Journal of Indigenous Peoples",
        idn: true,
    },
    {
        title: "Empowering communities through data literacy: A qualitative study exploring Indigenous Australian perceptions, engagement and understanding of data.",
        description: "",
        date: "2024",
        author: ["Cook B., Corporal S., Aleckson J., Blackman R., Kefford G., Lovell D., Mengersen K."],
        img: "",
        url: "https://doi.org/10.15353/joci.v20i1.5707",
        publisher: "The Journal of Community Informatics, 20(1), 5707.",
        idn: true,
    },
    {
        title: "IDN Roundtable: Developing & Adopting Indigenous Data Governance Frameworks Defining Indigenous Data",
        description: "",
        date: "2024-04-04",
        author: ["Indigenous Data Network"],
        img: "",
        url: "",
        publisher: "Melbourne, Victoria, Australia",
        idn: true,
    },
    {
        title: "Indigenous Data Governance in Australia: Towards a national framework.",
        description: "",
        date: "2023",
        author: ["Rose, J., Langton, M., Smith, K., & Clinch, D."],
        img: "",
        url: "https://doi.org/10.18584/iipj.2023.14.1.10987",
        publisher: "The International Indigenous Policy Journal, 14(1), 1–30.",
        idn: true,
    },
    {
        title: "The Future Impact of Artificial Intelligence on First Nations Communities: Opportunities and Risks",
        description: "",
        date: "2025",
        author: ["Turner, K."],
        img: "",
        url: "",
        publisher: "Paul Ramsay Foundation Fellowship Report, Brotherhood of St Laurence, Melbourne, Victoria",
        idn: false,
    },
    {
        title: "A/HRC/60/66: Right of Indigenous Peoples to data, including with regard to data collection and disaggregation.",
        description: "",
        date: "2025-08-06",
        author: ["Expert Mechanism on the Rights of Indigenous Peoples (EMRIP)"],
        img: "",
        url: "https://www.ohchr.org/en/documents/thematicreports/ahrc6066-right-indigenous-peoples-data-including-regard-data-collection",
        publisher: "Office of the High Commissioner for Human Rights.",
        idn: false,
    },
    {
        title: "Data Catalog Vocabulary (DCAT) — Version 3 (W3C Recommendation)",
        description: "",
        date: "2024-08-22",
        author: ["World Wide Web Consortium"],
        img: "",
        url: "https://www.w3.org/TR/vocab-dcat-3",
        publisher: "",
        idn: false,
    },
    {
        title: "Taking Control of Our Data: A Discussion Paper on Indigenous Data Governance for Aboriginal and Torres Strait Islander People and Communities",
        description: "",
        date: "2024",
        author: ["Lowitja Institute"],
        img: "",
        url: "https://doi.org/10.48455/rtvd-7782",
        publisher: "Discussion Paper, Melbourne",
        idn: false,
    },
    {
        title: "Guidelines for First Nations Collection Description",
        description: "",
        date: "2023",
        author: ["Raven, Tui."],
        img: "",
        url: "",
        publisher: "Australian Institute of Aboriginal and Torres Strait Islander Studies (AIATSIS), the Australian Library and Information Association (ALIA), the Council of Australian University Librarians (CAUL), CAVAL, National and State Libraries Australasia (NSLA)",
        idn: false,
    },
    {
        title: "WHO guideline on data integrity",
        description: "",
        date: "2021",
        author: ["World Health Organization"],
        img: "",
        url: "https://www.who.int/publications/m/item/annex-4-trs-1033",
        publisher: "Annex 4, WHO Technical Report Series, No. 1033",
        idn: false,
    },
    {
        title: "Operationalizing the CARE and FAIR principles for Indigenous data futures",
        description: "",
        date: "2021",
        author: ["Carroll S. R., Herczog E., Hudson M., et al."],
        img: "",
        url: "https://doi.org/10.1038/s41597-021-00892-0",
        publisher: "Scientific Data, 8(1), 108",
        idn: false,
    },
    {
        title: "The CARE principles for Indigenous data governance",
        description: "",
        date: "2020",
        author: ["Carroll S. R., Garba I., Figueroa-Rodríguez O., Holbrook J., Lovett R., Materechera S., Parsons M., Raseroka K., Rodriguez-Lonebear D., Rowe R."],
        img: "",
        url: "https://doi.org/10.5334/dsj-2020-043",
        publisher: "Data Science Journal, 19(1), 43",
        idn: false,
    },
    {
        title: "The TRUST Principles for digital repositories",
        description: "",
        date: "2020",
        author: ["Lin, D., Crabtree, J., Dillo, I., Downs, R. R., Edmunds, R., Giaretta, D., De Giusti, M., et al."],
        img: "",
        url: "https://doi.org/10.1038/s41597-020-0486-7",
        publisher: "Scientific Data, 7*, 144",
        idn: false,
    },
    {
        title: "ODRL Vocabulary & Expression 2.2 (W3C Recommendation)",
        description: "",
        date: "2018-02-15",
        author: ["Iannella, R., Steidl, M., Myles, S., & Rodríguez-Doncel, V."],
        img: "",
        url: "https://www.w3.org/TR/odrl-vocab/",
        publisher: "World Wide Web Consortium",
        idn: false,
    },
    {
        title: "Five Safes: Designing data access for research",
        description: "",
        date: "2016",
        author: ["Desai, T., Ritchie, F., & Welpton, R."],
        img: "",
        url: "https://www2.uwe.ac.uk/faculties/BBS/Documents/1601.pdf",
        publisher: "Economics Working Paper Series 1601. University of the West of England, Bristol",
        idn: false,
    },
    {
        title: "The FAIR guiding principles for scientific data management and stewardship",
        description: "",
        date: "2016",
        author: ["Wilkinson, M. D., Dumontier, M., Aalbersberg, I. J., Appleton, G., Axton, M., Baak, A., Blomberg, N., et al."],
        img: "",
        url: "https://doi.org/10.1038/sdata.2016.18",
        publisher: "Scientific Data, 3, 160018",
        idn: false,
    },
    {
        title: "Indigenous data sovereignty: Toward an agenda",
        description: "",
        date: "2016",
        author: ["Kukutai, T., & Taylor, J. (Eds.)."],
        img: "",
        url: "https://doi.org/10.22459/CAEPR38.11.2016",
        publisher: "ANU Press",
        idn: false,
    },
];
